### ISSUE TITLE
Editing image (e.g. scaling, cropping) breaks image

### ISSUE THREAD

**Issue by tallmorgan** [deliciousbrains/wp-amazon-s3-and-cloudfront#221]
On a fresh install of WordPress, enabling just AWS Web Services and AWS S3 plugins works wonderfully for uploading images to Amazon. The issue I'm experiencing is when trying to edit the image, e.g. scaling/cropping, it breaks the image.

An immediate solution for power users is to use another tool e.g. Photoshop, GIMP, etc., to resize the image before uploading, but for regular WP admin users, it's not a viable option.

Love the plugin! Is fixing this in the roadmap? See following attachments (plugin screen, broken image, settings page).

I can provide login credentials for the sandbox per request.

![aws-1](https://cloud.githubusercontent.com/assets/1131915/5952700/466cb470-a731-11e4-9abe-b3f2d93ce401.jpg)
![aws-2](https://cloud.githubusercontent.com/assets/1131915/5952701/46700ba2-a731-11e4-9975-edcca6424712.jpg)
![aws-3](https://cloud.githubusercontent.com/assets/1131915/5952702/4672efa2-a731-11e4-8bfc-9a06d42e8d87.jpg)

**Comment by A5hleyRich** [comment]
This issue has been resolved and will be available in the next release.

**Comment by 20minutos** [comment]
Hi!

we are having same -or similar- issue (only if "Remove Files From Server" options is enabled) when try to rotate (or any transformation) an image and save changes.

PHP error message:
```
PHP Warning:  fopen(http://MY_BUCKET_URL/files/2015/03/image-e1426077938745.jpg): failed to open stream: HTTP wrapper does not support writeable connections in /home/blog/wordpress-mu/wp-includes/class-wp-image-editor.php on line 424 
```

Any estimate about when next release will be available?

Thanks!!! (and great plugin!!)

**Comment by mrbm** [comment]
Has the next resolved release been made available? I'm getting a problem with the editing of image as well, tried to do a basic rotation, but the "working on it" circle kept spinning on the update. And then when i went to update the post it created a link reference to: imagename-e1427674875848.jpg when the original image was imagename.jpg...and left the original image still on the s3 server. Hope that helps with debugging. Thanks!

**Comment by A5hleyRich** [comment]
The next release isn't available just yet and we don't currently have a release date. But it's well underway.

**Comment by wilrevehl** [comment]
Posted this on the plugin support thread and then found this here so thought I'd share. I looked into the issue and Amazon wrote a php class to act as a stream protocol handler so these files can use functions like fopen. It's called aS3StreamWrapper

Here're the details: https://forums.aws.amazon.com/thread.jspa?messageID=283440

Let me know if you need any help with this. Thanks!

**Comment by ggallo** [comment]
My problem is likely a duplicate of this: attempting an image edit does not "break" the image so to speak, but the edit page presents me with a broken link. Is this also covered under the future release? Thanks for such a great plugin. Looking forward to the pro version!

![screen shot 2015-04-29 at 4 58 56 pm](https://cloud.githubusercontent.com/assets/3633936/7401363/6c47359c-ee91-11e4-9853-14ccb383d8eb.png)
![screen shot 2015-04-29 at 4 59 11 pm](https://cloud.githubusercontent.com/assets/3633936/7401362/6c45cbda-ee91-11e4-92f6-233b8af10ed4.png)

**Comment by polevaultweb** [comment]
@ggallo do you have the setting 'Remove files from server' turned on? If so then this issue is fixed in the next release.

**Comment by ggallo** [comment]
Thanks @polevaultweb I do have that setting on.

**Comment by kara-todd** [comment]
@A5hleyRich Is there a release which contains this fix? I see it's marked as 'resolved' but downloading the latest stable version (0.8.2) it's still causing some issues for us. If there isn't a full release, is there a hot fix or something I can add it to at least temporarily patch this?

**Comment by mrbm** [comment]
Would love that hot fix too...stuck in the mud here waiting.

**Comment by A5hleyRich** [comment]
@kara-todd @mrbm The release that contains the fix isn't available yet. We haven't got a hotfix available as there are too many changes required to get this working, hence it being shipped in the next release. The only work around at present is to disable the option 'Remove files from server' and copy the existing S3 files back to the server if they're not already present.

**Comment by mrbm** [comment]
perhaps there should be an "intermediate" release to fix the broken items before releasing the version with new features...?

**Comment by kara-todd** [comment]
@A5hleyRich We don't have the 'Remove files from server' option checked, but I'm also seeing this behavior with plugins which generate new images sizes. In particular (right now) [Meta slider](https://wordpress.org/plugins/ml-slider/) which dynamically creates a new image size. For some reason this is still causing the text-to-screen issue even though the original image assets should be there... Can you elaborate a bit on what the problem is? Maybe I can track down the particular issue I'm experiencing on the Meta slider side and patch things there?

**Comment by A5hleyRich** [comment]
@mrbm No intermediate release is planned.

@kara-todd This may be a separate issue. We'll test with Meta Slider and let you know.

**Comment by mrbm** [comment]
So the plugin is broken, there is no timeline, and no intermediate
releases....whats the plan here kids?

**Comment by kara-todd** [comment]
@A5hleyRich were you able to confirm that the Meta Slider issue is related to this problem? Or is it indeed something we can pursue a fix for separately?

**Comment by MasterRoot24** [comment]
:+1: for me on this issue.

I would love some idea of when we can expect a release.

Thanks.

**Comment by kara-todd** [comment]
@A5hleyRich Since there's no ETA on the release for this issue would you mind pointing where this issue centers around? Or the commit lines that address this issue? This is starting to become a thorn in the side of our client, and even if I have to duct tape something together for a bit I'd like to take a crack at it. :)

**Comment by A5hleyRich** [comment]
@kara-todd the release is due this week, pending no further issues.

**Comment by kara-todd** [comment]
@A5hleyRich awesome! :D Glad to hear it! Thanks

**Comment by polevaultweb** [comment]
This was fixed as of 0.9

**Comment by kara-todd** [comment]
@polevaultweb I'm still seeing this issue when using GD Image. The following error is thrown:

`PHP Warning:  fopen('[...]'): failed to open stream: HTTP wrapper does not support writeable connections in /wp-includes/class-wp-image-editor.php on line 427` and the image binary is printed to the screen.

With ImageMagick `make_image` is called inside a try-catch block and the exception is caught, but in GD Image there is no try-catch wrapper.

In both instances `make_image` fails to actually generate a new image when invoked through `$image = wp_get_image_editor( 'url' ); $image->crop(); $image->save();`

There are a few plugins which make use of this. Is there a way to work with this behavior? So that these plugins can still work with the S3 url?

**Comment by polevaultweb** [comment]
@kara-todd which plugins are you using so I can recreate?

**Comment by kara-todd** [comment]
@polevaultweb We are using [Metaslider](https://wordpress.org/plugins/ml-slider/) (with SmartCrop) and [OTF Regenerate Thumbnails](https://wordpress.org/plugins/otf-regenerate-thumbnails/)

**Comment by polevaultweb** [comment]
@kara-todd thanks for that, I've raised an issue on our internal repo to investigate.
